### ISSUE TITLE
Fields of Student Doctype

### ISSUE THREAD

**Issue by its4nas** [SanU-Development-Team/Academia#7]
**I would like you to add the fields of the 'Student' Doctype to use the names of these fields in my project.**
these fields maybe like: 
- Student ID,
-  Student Name,
-  Date of Birth,
-  Student Image,
-  College,
-  Major, 
-  Level,
-  Studying System {عام او موازي},
- etc...

**Comment by BakrAldubai** [comment]
The College, Major, Level, Studying System {عام او موازي} will not be added to the 'Student' Doctype they will be added in other doctypes that handles the enrollment process.
